/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Indexer API
 * The Querys for the NFT Indexer
 * OpenAPI spec version: 1.0
 */
import type { _CollectionResponseDtoCount } from './_collectionResponseDtoCount';
import type { CollectionResponseDtoPolicy } from './collectionResponseDtoPolicy';

/**
 * Response schema for a collection
 */
export interface CollectionResponseDto {
  type: string;
  verified: boolean;
  volume: number;
  description: string;
  name: string;
  createdAt: string;
  updatedAt: string;
  imageUrl: string;
  bannerUrl?: string;
  _count: _CollectionResponseDtoCount;
  /** Policy data information */
  policy?: CollectionResponseDtoPolicy;
  attributesKP?: string[];
  listingCount?: number;
}
