/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Indexer API
 * The Querys for the NFT Indexer
 * OpenAPI spec version: 1.0
 */
import type { Collection } from './collection';
import type { Wallet } from './wallet';

export interface CollectionOffer {
  collectionType: string;
  kiosk: string;
  offerId: string;
  offerCap: string;
  policyId: string;
  price: number;
  marketplaceFee: number;
  royaltyFee: number;
  ownerWalletAddress: string;
  kioskStandard: boolean;
  createdAt: string;
  collection: Collection;
  owner: Wallet;
}
