/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Indexer API
 * The Querys for the NFT Indexer
 * OpenAPI spec version: 1.0
 */

/**
 * Policy data information
 */
export type CollectionResponseDtoPolicy = {
  id: string;
  rules: string[];
  balance: string;
  percentage: number;
  minimum: number;
};
