/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Indexer API
 * The Querys for the NFT Indexer
 * OpenAPI spec version: 1.0
 */

export type FindManyCollectionsDtoOrderByVolume = typeof FindManyCollectionsDtoOrderByVolume[keyof typeof FindManyCollectionsDtoOrderByVolume];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FindManyCollectionsDtoOrderByVolume = {
  asc: 'asc',
  desc: 'desc',
} as const;
