/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Indexer API
 * The Querys for the NFT Indexer
 * OpenAPI spec version: 1.0
 */
import type { FindNftActivityInputDtoQuery } from './findNftActivityInputDtoQuery';

/**
 * Find NFT activity input parameters
 */
export interface FindNftActivityInputDto {
  tokenId: string;
  /** NFT activity type */
  query?: FindNftActivityInputDtoQuery;
}
