/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Indexer API
 * The Querys for the NFT Indexer
 * OpenAPI spec version: 1.0
 */

/**
 * NFT activity type
 */
export type FindNftActivityInputDtoQuery = typeof FindNftActivityInputDtoQuery[keyof typeof FindNftActivityInputDtoQuery];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FindNftActivityInputDtoQuery = {
  transfer: 'transfer',
  purchase: 'purchase',
  listing: 'listing',
  delist: 'delist',
  offer: 'offer',
  mint: 'mint',
  burn: 'burn',
  offerAccepted: 'offerAccepted',
  mint_owner_not_found: 'mint_owner_not_found',
  ownership_error: 'ownership_error',
  offerDeclined: 'offerDeclined',
  offerRevoked: 'offerRevoked',
  collectionOfferAccepted: 'collectionOfferAccepted',
  other: 'other',
} as const;
