/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Indexer API
 * The Querys for the NFT Indexer
 * OpenAPI spec version: 1.0
 */

/**
 * Find listings by type
 */
export interface FindListingsByTypeDto {
  type?: string;
}
