/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Indexer API
 * The Querys for the NFT Indexer
 * OpenAPI spec version: 1.0
 */
import type { FindManyNftInputDtoBasic } from './findManyNftInputDtoBasic';

/**
 * Find many NFTs input with ordering
 */
export interface FindManyNftInputDto {
  /** Find many NFTs parameters */
  basic: FindManyNftInputDtoBasic;
  orderBy?: unknown;
}
