/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Indexer API
 * The Querys for the NFT Indexer
 * OpenAPI spec version: 1.0
 */
import type { FindManyCollectionsDtoOrderByVerified } from './findManyCollectionsDtoOrderByVerified';
import type { FindManyCollectionsDtoOrderByVolume } from './findManyCollectionsDtoOrderByVolume';

/**
 * Order by parameters for collections
 */
export type FindManyCollectionsDtoOrderBy = {
  verified?: FindManyCollectionsDtoOrderByVerified;
  volume?: FindManyCollectionsDtoOrderByVolume;
};
