/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Indexer API
 * The Querys for the NFT Indexer
 * OpenAPI spec version: 1.0
 */
import type { FindManyCollectionsDtoOrderBy } from './findManyCollectionsDtoOrderBy';
import type { FindManyCollectionsDtoWhere } from './findManyCollectionsDtoWhere';
import type { FindManyCollectionsDtoInclude } from './findManyCollectionsDtoInclude';

export interface FindManyCollectionsDto {
  /**
   * @minimum 1
   * @maximum 100
   */
  limit: number;
  /** @minimum 0 */
  skip?: number;
  /** Order by parameters for collections */
  orderBy?: FindManyCollectionsDtoOrderBy;
  /** Where parameters for filtering collections */
  where?: FindManyCollectionsDtoWhere;
  /** Include parameters for collections */
  include?: FindManyCollectionsDtoInclude;
}
