/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Indexer API
 * The Querys for the NFT Indexer
 * OpenAPI spec version: 1.0
 */
import type { FindManyNftActivityDtoActivityType } from './findManyNftActivityDtoActivityType';

/**
 * Find many NFT activities parameters
 */
export interface FindManyNftActivityDto {
  type: string;
  /**
   * @minimum 1
   * @maximum 150
   */
  limit?: number;
  /** @minimum 0 */
  skip?: number;
  /** NFT activity type */
  activityType?: FindManyNftActivityDtoActivityType;
  orderBy?: unknown;
}
