/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Indexer API
 * The Querys for the NFT Indexer
 * OpenAPI spec version: 1.0
 */

/**
 * Include parameters for collections
 */
export type FindManyCollectionsDtoInclude = {
  CollectionOffer?: boolean;
};
