/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Indexer API
 * The Querys for the NFT Indexer
 * OpenAPI spec version: 1.0
 */

/**
 * Find many NFTs parameters
 */
export type FindManyNftInputDtoBasic = {
  type: string;
  listings: boolean;
  offers: boolean;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /** @minimum 0 */
  skip?: number;
};
