/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Indexer API
 * The Querys for the NFT Indexer
 * OpenAPI spec version: 1.0
 */
import type { Wallet } from './wallet';

export interface Kiosk {
  kioskOwnercap: string;
  kiosk: string;
  personal: boolean;
  ownerWalletAddress: string;
  owner: Wallet;
}
