/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Indexer API
 * The Querys for the NFT Indexer
 * OpenAPI spec version: 1.0
 */

export type LaunchpadCollectionStateDtoState = typeof LaunchpadCollectionStateDtoState[keyof typeof LaunchpadCollectionStateDtoState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LaunchpadCollectionStateDtoState = {
  Initialized: 'Initialized',
  Approved: 'Approved',
  Rejected: 'Rejected',
  Paused: 'Paused',
  Resumed: 'Resumed',
  Pending: 'Pending',
  Completed: 'Completed',
  Active: 'Active',
} as const;
