/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Indexer API
 * The Querys for the NFT Indexer
 * OpenAPI spec version: 1.0
 */

export type LaunchpadPhaseDtoPhase = typeof LaunchpadPhaseDtoPhase[keyof typeof LaunchpadPhaseDtoPhase];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LaunchpadPhaseDtoPhase = {
  whitelist: 'whitelist',
  custom: 'custom',
  public: 'public',
} as const;
