/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Indexer API
 * The Querys for the NFT Indexer
 * OpenAPI spec version: 1.0
 */
import type { NftMetadata } from './nftMetadata';
import type { DynamicNftAttribute } from './dynamicNftAttribute';
import type { Listing } from './listing';
import type { Collection } from './collection';
import type { Wallet } from './wallet';
import type { Offer } from './offer';
import type { StaticNftAttribute } from './staticNftAttribute';

export interface Nft {
  tokenId: string;
  type: string;
  name: string;
  imageUrl: string;
  metadata: NftMetadata;
  rarity: string;
  rarityScore?: number;
  description: string;
  kiosk: string;
  holder: string;
  digests: string[];
  createdAt: string;
  updatedAt: string;
  volume: number;
  walletAddress?: string;
  dynamicAttribute: DynamicNftAttribute[];
  listing?: Listing;
  collection: Collection;
  wallet?: Wallet;
  offers: Offer[];
  staticAttribute: StaticNftAttribute[];
}
