/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Indexer API
 * The Querys for the NFT Indexer
 * OpenAPI spec version: 1.0
 */
import type { NftEventDescription } from './nftEventDescription';
import type { Wallet } from './wallet';

export interface NftEvent {
  collectionType: string;
  tokenId: string;
  digest: string;
  price?: number;
  marketplaceFee?: number;
  royaltyFee?: number;
  description?: NftEventDescription;
  sender: string;
  reciever?: string;
  type: string;
  createdAt: string;
  walletReciever?: Wallet;
  walletSender: Wallet;
}
