/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Indexer API
 * The Querys for the NFT Indexer
 * OpenAPI spec version: 1.0
 */
import type { Wallet } from './wallet';
import type { Nft } from './nft';

export interface Offer {
  collectionType: string;
  kiosk: string;
  offerId: string;
  offerCap: string;
  tokenId: string;
  price: number;
  marketplaceFee: number;
  royaltyFee: number;
  ownerWalletAddress: string;
  kioskStandard: boolean;
  createdAt: string;
  updatedAt: string;
  nftId?: string;
  owner: Wallet;
  nft: Nft;
}
