/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Indexer API
 * The Querys for the NFT Indexer
 * OpenAPI spec version: 1.0
 */
import type { Nft } from './nft';

export interface StaticNftAttribute {
  nftTokenId: string;
  collectionType: string;
  traitType: string;
  value: string;
  rarity?: string;
  createdAt: string;
  updatedAt: string;
  baseNft: Nft;
}
