/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Indexer API
 * The Querys for the NFT Indexer
 * OpenAPI spec version: 1.0
 */
import type { Listing } from './listing';
import type { Offer } from './offer';
import type { CollectionOffer } from './collectionOffer';
import type { Kiosk } from './kiosk';
import type { Nft } from './nft';
import type { NftEvent } from './nftEvent';
import type { WhiteListAddress } from './whiteListAddress';

export interface Wallet {
  address: string;
  personalFee?: number;
  listings: Listing[];
  offers: Offer[];
  collectionOffers: CollectionOffer[];
  kiosks: Kiosk[];
  nfts: Nft[];
  nftEventsSender: NftEvent[];
  nftEventsReciever: NftEvent[];
  whietListAddresses: WhiteListAddress[];
}
