/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Indexer API
 * The Querys for the NFT Indexer
 * OpenAPI spec version: 1.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  NftEvent,
  Wallet
} from '.././model';




  export const Wallet_find = <TData = AxiosResponse<Wallet>>(
    address: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:3333/wallet/${address}`,options
    );
  }
export const Wallet_findActivity = <TData = AxiosResponse<NftEvent[]>>(
    address: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:3333/wallet/${address}/activity`,options
    );
  }
export type WalletFindResult = AxiosResponse<Wallet>
export type WalletFindActivityResult = AxiosResponse<NftEvent[]>
