/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Indexer API
 * The Querys for the NFT Indexer
 * OpenAPI spec version: 1.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  FindManyNftActivityDto,
  FindManyNftInputDto,
  FindNftActivityInputDto,
  FindNftsByAttributesInputDto,
  Nft,
  NftEvent
} from '.././model';




  export const Nft_One = <TData = AxiosResponse<Nft>>(
    address: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `http://localhost:3333/nft/${address}`,options
    );
  }
export const Nft_ManyByType = <TData = AxiosResponse<Nft[]>>(
    findManyNftInputDto: FindManyNftInputDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `http://localhost:3333/nft/type`,
      findManyNftInputDto,options
    );
  }
export const Nft_Attributes = <TData = AxiosResponse<Nft[]>>(
    findNftsByAttributesInputDto: FindNftsByAttributesInputDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `http://localhost:3333/nft/attribute`,
      findNftsByAttributesInputDto,options
    );
  }
export const Nft_Activity = <TData = AxiosResponse<NftEvent[]>>(
    findNftActivityInputDto: FindNftActivityInputDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `http://localhost:3333/nft/activity`,
      findNftActivityInputDto,options
    );
  }
export const Nft_ManyByActivity = <TData = AxiosResponse<NftEvent[]>>(
    findManyNftActivityDto: FindManyNftActivityDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `http://localhost:3333/nft/activity/many`,
      findManyNftActivityDto,options
    );
  }
export type NftOneResult = AxiosResponse<Nft>
export type NftManyByTypeResult = AxiosResponse<Nft[]>
export type NftAttributesResult = AxiosResponse<Nft[]>
export type NftActivityResult = AxiosResponse<NftEvent[]>
export type NftManyByActivityResult = AxiosResponse<NftEvent[]>
