/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Indexer API
 * The Querys for the NFT Indexer
 * OpenAPI spec version: 1.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  Collection,
  CollectionOffer,
  FindCollectionOffersDto,
  FindListingsByIdDto,
  FindListingsByTypeDto,
  FindManyOffersDto,
  FindOneOfferByIdDto,
  FindOneOfferByTokenIdDto,
  LaunchpadCollection,
  LaunchpadCollectionStateDto,
  LaunchpadFindByDto,
  LaunchpadPhaseDto,
  Offer
} from '.././model';




  export const Marketplace_findListing = <TData = AxiosResponse<Collection>>(
    findListingsByIdDto: FindListingsByIdDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `http://localhost:3333/marketplace/listing`,
      findListingsByIdDto,options
    );
  }
export const Marketplace_findManyListings = <TData = AxiosResponse<Collection[]>>(
    findListingsByTypeDto: FindListingsByTypeDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `http://localhost:3333/marketplace/listings/many`,
      findListingsByTypeDto,options
    );
  }
export const Marketplace_findOffers = <TData = AxiosResponse<Offer>>(
    findOneOfferByIdDto: FindOneOfferByIdDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `http://localhost:3333/marketplace/offers/id`,
      findOneOfferByIdDto,options
    );
  }
export const Marketplace_findOfferByTokenId = <TData = AxiosResponse<Offer>>(
    findOneOfferByTokenIdDto: FindOneOfferByTokenIdDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `http://localhost:3333/marketplace/offers/token`,
      findOneOfferByTokenIdDto,options
    );
  }
export const Marketplace_findManyOffers = <TData = AxiosResponse<Offer[]>>(
    findManyOffersDto: FindManyOffersDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `http://localhost:3333/marketplace/offers/many`,
      findManyOffersDto,options
    );
  }
export const Marketplace_findCollectionOffers = <TData = AxiosResponse<CollectionOffer[]>>(
    findCollectionOffersDto: FindCollectionOffersDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `http://localhost:3333/marketplace/collection-offers`,
      findCollectionOffersDto,options
    );
  }
export const Marketplace_findAllLaunchpads = <TData = AxiosResponse<LaunchpadCollection[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `http://localhost:3333/marketplace/launchpad`,undefined,options
    );
  }
export const Marketplace_findLaunchpadOne = <TData = AxiosResponse<LaunchpadCollection>>(
    launchpadFindByDto: LaunchpadFindByDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `http://localhost:3333/marketplace/launchpad/one`,
      launchpadFindByDto,options
    );
  }
export const Marketplace_findLaunchpadByPhase = <TData = AxiosResponse<LaunchpadCollection[]>>(
    launchpadPhaseDto: LaunchpadPhaseDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `http://localhost:3333/marketplace/launchpad/phase`,
      launchpadPhaseDto,options
    );
  }
export const Marketplace_findLaunchpadByState = <TData = AxiosResponse<LaunchpadCollection[]>>(
    launchpadCollectionStateDto: LaunchpadCollectionStateDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `http://localhost:3333/marketplace/launchpad/state`,
      launchpadCollectionStateDto,options
    );
  }
export const Marketplace_findLaunchpadBySdk = <TData = AxiosResponse<LaunchpadCollection>>(
    launchpadFindByDto: LaunchpadFindByDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `http://localhost:3333/marketplace/launchpad/sdk`,
      launchpadFindByDto,options
    );
  }
export type MarketplaceFindListingResult = AxiosResponse<Collection>
export type MarketplaceFindManyListingsResult = AxiosResponse<Collection[]>
export type MarketplaceFindOffersResult = AxiosResponse<Offer>
export type MarketplaceFindOfferByTokenIdResult = AxiosResponse<Offer>
export type MarketplaceFindManyOffersResult = AxiosResponse<Offer[]>
export type MarketplaceFindCollectionOffersResult = AxiosResponse<CollectionOffer[]>
export type MarketplaceFindAllLaunchpadsResult = AxiosResponse<LaunchpadCollection[]>
export type MarketplaceFindLaunchpadOneResult = AxiosResponse<LaunchpadCollection>
export type MarketplaceFindLaunchpadByPhaseResult = AxiosResponse<LaunchpadCollection[]>
export type MarketplaceFindLaunchpadByStateResult = AxiosResponse<LaunchpadCollection[]>
export type MarketplaceFindLaunchpadBySdkResult = AxiosResponse<LaunchpadCollection>
